{
    "name": "Event Management & Digital Technology",
    "version": "19.0.1.0.0",
    "summary": "End-to-end committee, participant, badge, check-in and incident management",
    "category": "Marketing/Events",
    "author": "Custom",
    "license": "LGPL-3",
    "depends": ["event", "mail"],
    "external_dependencies": {"python": ["qrcode"]},
    "data": [
        "security/event_management_security.xml",
        "security/ir.model.access.csv",
        "security/event_management_rules.xml",
        "data/event_management_sequences.xml",
        "data/event_management_data.xml",
        "data/event_management_cron.xml",
        "views/event_event_views.xml",
        "views/committee_views.xml",
        "views/activity_views.xml",
        "views/participant_views.xml",
        "views/badge_views.xml",
        "views/incident_views.xml",
        "views/audit_views.xml",
        "report/event_management_reports.xml",
        "views/event_management_menus.xml",
    ],
    "application": True,
    "installable": True,
}
